# Generated by Django 5.0.11 on 2025-02-03 09:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDeletionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_mins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='file-shared/')),
                ('text', models.TextField(null=True)),
                ('access_code', models.CharField(max_length=10, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
